### ISSUE TITLE
Is it possible to build learnings from multiple tags?

### ISSUE THREAD

**Issue by guillegr123** [winkjs/wink-ner#10]
For example, if I want to identify a price, is there a way to define a learning entry composed of a currency token followed by a number token?

**Comment by sanjayaksaxena** [comment]
Hi @guillegr123 

It is possible with [wink-tokenizer](http://winkjs.org/wink-tokenizer/) and you don't need `wink-ner`. The tokenizer has an [token's finger printing](http://winkjs.org/wink-tokenizer/Tokenizer.html#getTokensFP) API, which will help you achieve this. 

To illustrate, if you tokenize `'enjoy extra cheese for just $10'` then its finger print will be `"wwwwwrn"`, from which you can easily identify the amount token using either JS regex or possibly indexOf() function. The objective here is to spot `rn|nr` pattern and its index.

You will be using `wink-tokenizer` already as it is a [prerequisite](http://winkjs.org/wink-ner/#getting-started) for `wink-ner`.

Hope it helps; feel free to reach us if you need further assistance.

Best,
Sanjaya

**Comment by guillegr123** [comment]
I'll try that, thank you very much Sanjaya.
