### ISSUE TITLE
Default training data file?

### ISSUE THREAD

**Issue by deemeetree** [winkjs/wink-ner#17]
Hello, nice package! Do you have a default training data file, so that I could train the model on some default settings to get it up and running? Rather than having to create the training data file myself? Thanks!

**Comment by sanjayaksaxena** [comment]
Hello @deemeetree 

We do not have any open source pre-trained models/training data for `wink-ner`. But we are working on a next generation, high performance nlp with multiple pre-trained models (includes NER), word vectors integration and a developer friendly API. We should be releasing it in open source shortly. Would you be interested in early access?

Best,
Sanjaya

**Comment by deemeetree** [comment]
@sanjayaksaxena definitely yes!

otherwise i'll have to use nlp.js from AXA but I kind of would be more into using your tool in my software.

**Comment by sanjayaksaxena** [comment]
Thank you @deemeetree for your interest. Please drop a mail at wink@graype.in and we will follow up with the next steps.
