### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by danielepolencic** [winkjs/wink-ner#18]
The examples shows how NER can identify and distinguish between Manchester (the city) vs Manchester United (the club).

However, I can't find a way to do the opposite.

Consider USA and United States of America. Both should be detected as the same entity.

Is this possible?

**Comment by rachnachakraborty** [comment]
Hello @danielepolencic 

Sure it will be able to recognize entities the other way round, if training data is prepared like in the sample below:

```javascript
 var trainingData = [
      { text: 'U S A', entityType: 'country', uid: 'US' },
      { text: 'U S', entityType: 'country', uid: 'US' },
      { text: 'United States of America', entityType: 'country', uid: 'US' },
      { text: 'U K', entityType: 'country', uid: 'UK' },
      { text: 'United Kingdom', entityType: 'country', uid: 'UK' },
      { text: 'England', entityType: 'country', uid: 'UK' }, 
];
```
for the following input string one can extract countries represented in more than 1 way.
```
'U.S.A. is on my itinerary this year. I  am visiting England in August end and should be off to the US by mid September'
```
The entities extracted are 

```javascript
{entityType: "country", originalSeq: ["U", ".", "S", ".", "A"], tag: "word", uid: "US", value: "u s a"}
{entityType: "country", originalSeq: ["England"], tag: "word", uid: "UK", value: "england"}
{entityType: "country", originalSeq: ["US"], tag: "word", uid: "US", value: "us"}
```
The key here is "uid" which works like a group id for the entities under the same umbrella.

Hope this helps.

Best,
Rachna

**Comment by danielepolencic** [comment]
I believe this answers my questions.
Reading the documentation I thought `uid` had to be unique.
Thanks for clarifying.
