### ISSUE TITLE
Connect wink-ner with wink-nlp ?

### ISSUE THREAD

**Issue by creadicted** [winkjs/wink-ner#21]
Hello, 
I play around with the library. My training set leads to a lot of wrong entityType assignments, but I want to test it a bit more. 
With my trained ner model. Is it possible to use that with wink-nlp? I haven't seen any docs for that. I would like to use the visualization features showcased in the wink-nlp with a custom annoted ner set.

**Comment by rachnachakraborty** [comment]
Hey @creadicted,

Thanks for exploring winkjs packages.

Firstly, you have mentioned about wrong entityType assignments, would appreciate if you can share a sample training set and your code to figure out a  solution.

Secondly, you can consider using the custom entities in wink-nlp to train the model.  The existing dataset will not suffice as the pattern definition works differently in wink-nlp.  Please go through the [Getting Started](https://winkjs.org/wink-nlp/getting-started.html) and [Custom Entities concepts and examples](https://winkjs.org/wink-nlp/custom-entities.html) to explore further.

Cheers!

Rachna

**Comment by creadicted** [comment]
The reason for the type assignment was based on my training data. With more filters I started to clean everything up. 
> Secondly, you can consider using the custom entities in wink-nlp to train the model

I did so but if I use `learnCustomEntities`  like in the [example](https://winkjs.org/wink-nlp/custom-entities.html), none will be recognized.  Am I missing something? 


Super simple example: 

```typescript
        const text = "Allow solution to cool at room temperature for at least 30min, but overnight on bench is best."
        const patterns = [
          { name: 'temperature', patterns: ['room temperature'] },
          { name: 'time', patterns: ['overnight'] },
        ];
        await this.nlp.learnCustomEntities(patterns);

        const doc = this.nlp.readDoc(text);

        doc.entities().each((e) => e.markup());

        resolve({
          sentences: doc.sentences().out(),
          entities: doc.entities().out(),
          tokens: doc.tokens().out(),
          markup: doc.out(its.markedUpText),
          customEntities: doc.customEntities().out(its.detail),
        });
```

result: 

```json
{
  "doc": {
    "sentences": [
      "Allow solution to cool at room temperature for at least 30min, but overnight on bench is best."
    ],
    "entities": [
      "30"
    ],
    "tokens": [
      "Allow",
      "solution",
      "to",
      "cool",
      "at",
      "room",
      "temperature",
      "for",
      "at",
      "least",
      "30",
      "min",
      ",",
      "but",
      "overnight",
      "on",
      "bench",
      "is",
      "best",
      "."
    ],
    "markup": "Allow solution to cool at room temperature for at least <mark>30</mark>min, but overnight on bench is best.",
    "customEntities": [
      {
        "value": "room temperature",
        "type": "temperature"
      },
      {
        "value": "overnight",
        "type": "time"
      }
    ]
  },
  "sentence": "Allow solution to cool at room temperature for at least 30min, but overnight on bench is best."
}
```

**Comment by rachnachakraborty** [comment]
Hello @creadicted,

Apologies, I missed sharing the following API links which contain configuration details to address your requirements. 

1. [Learn Custom Entities](https://winkjs.org/wink-nlp/learn-custom-entities.html)
2. [Custom Entities](https://winkjs.org/wink-nlp/custom-entities-method.html)

The first link has lots going in to handle the nuances of defining custom entities patterns. Hope this helps!

Best,
Rachna

**Comment by creadicted** [comment]
I tested wink-nlp with the Custom Entities but did not realize that they are not stored in `entities(`) but in `customEntities()`. So I thought I missed something. Thank you for the links.
